---

In [1]:
from pathlib import Path

path = Path().absolute()

In [8]:
cd ../

c:\Users\c10nGp4\OneDrive\Documents\GitHub\imbalance-multi-classification


In [3]:
import pickle
import time

---

### Instantiate Classifier
---

In [30]:
from pipeline.classification import Classification

clf = Classification()

2023-06-25 09:22:56 INFO: DOWNLOAD STANZA MODEL


2023-06-25 09:22:58 INFO: Downloading default packages for language: id (Indonesian) ...
2023-06-25 09:22:58 INFO: File exists: C:\Users\c10nGp4\stanza_resources\id\default.zip
2023-06-25 09:23:00 INFO: Finished downloading models and saved to C:\Users\c10nGp4\stanza_resources.
2023-06-25 09:23:00 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES


2023-06-25 09:23:00 INFO: LOAD STANZA PIPELINE: tokenize,mwt,pos,lemma


2023-06-25 09:23:08 INFO: Loading these models for language: id (Indonesian):
| Processor | Package |
-----------------------
| tokenize  | gsd     |
| mwt       | gsd     |
| pos       | gsd     |
| lemma     | gsd     |

2023-06-25 09:23:08 INFO: Using device: cuda
2023-06-25 09:23:08 INFO: Loading: tokenize
2023-06-25 09:23:10 INFO: Loading: mwt
2023-06-25 09:23:10 INFO: Loading: pos
2023-06-25 09:23:11 INFO: Loading: lemma
2023-06-25 09:23:11 INFO: Done loading processors!


### Load Data
---

In [5]:
# import pandas as pd

# # Load dataset
# training_set_df = pd.read_csv(path / "assets/datasets/training-set-1.csv", delimiter=";")

# # Get X and y from dataset
# X_train = list(training_set_df["texts"])
# y_train = list(training_set_df["targets"])

#### Get random samples
---

In [6]:
# from random import sample

In [7]:
# sample([x for x in X_train if len(x) <= 50 and "gugup" in x], 5)

#### Example of a dataset
---

In [31]:
X_temp = [
    "<b>Saya senang bisa melihat 🎆 bersamamu</b>",
    "Saya merasa benar-benar dirugikan dirinya!!!!",
    "Video menyeramkan lainnya: https://www.youtube.com/shorts/ZIl2iiHy1oM. ***JANGAN DILIHAT KALAU TIDAK BERANI***",
    "Saya merasa kesepian dan terisolasi akhir akhir ini",
    "saya merasa sangat sedih saya berharap saya mati",
    "saya merasa sedih hanya memikirkannya",
    "saya merasa patah hati dan sedih",
    "saya merasa sangat putus asa dan sedih",
    "Saya selalu merasa tidak diinginkan dan sedih",
    "saya merasa senang",
    "saya merasa cukup senang minggu ini",
    "saya sangat senang tapi saya merasa lelah",
    "saya merasakan cinta dan perhatian sekarang",
    "saya merasa disambut dan dicintai",
    "saya merasa dicintai",
    "saya merasa takut berada di dekat mereka",
    "saya merasa sangat ketakutan dan gugup",
    "saya merasa takut dan bodoh",
    "saya merasa takut",
    "saya sangat suka perasaan takut",
    "saya merasa seperti orang bodoh",
    "saya merasa bodoh tapi senang",
    "saya merasa sangat bodoh karena jujur",
    "saya merasa sangat bodoh dan malu",
    "saya merasa bodoh dan tidak diinginkan",
    "saya merasa kesal dan marah",
    "saya berteriak dengan perasaan sangat marah",
    "saya bahkan tidak bisa merasa marah karenanya",
    "saya merasa sedikit kesal hari ini",
    "saya bangun hari ini merasa kesal",
    "saya merasa sangat gemetar dan sedih",
    "saya menjadi bodoh merasa gugup"
]

y_temp = [
    "gembira",
    "marah",
    "takut",
    "sedih",
    "sedih",
    "sedih",
    "sedih",
    "sedih",
    "sedih",
    "gembira",
    "gembira",
    "gembira",
    "cinta",
    "cinta",
    "cinta",
    "takut",
    "takut",
    "takut",
    "takut",
    "takut",
    "sedih",
    "gembira",
    "sedih",
    "sedih",
    "sedih",
    "marah",
    "marah",
    "marah",
    "marah",
    "marah",
    "sedih",
    "sedih"
]

#### Split dataset
---

In [32]:
from sklearn.model_selection import train_test_split

X_temp_train, X_temp_test, y_temp_train, y_temp_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.2,
    random_state=42,
    stratify=y_temp
)

X_temp_train, X_temp_validation, y_temp_train, y_temp_validation = train_test_split(
    X_temp_train,
    y_temp_train,
    test_size=0.21,
    random_state=42,
    stratify=y_temp_train
)

In [33]:
print(len(X_temp_train))

# for x in X_temp_train:
#     print(x)

for y in y_temp_train:
    print(y)

19
takut
sedih
marah
sedih
sedih
marah
marah
gembira
gembira
takut
takut
sedih
takut
sedih
marah
sedih
sedih
cinta
gembira


In [34]:
print(len(X_temp_validation))

# for x in X_temp_validation:
#     print(x)

for y in y_temp_validation:
    print(y)

6
takut
sedih
gembira
marah
cinta
sedih


In [35]:
print(len(X_temp_test))

# for x in X_temp_test:
#     print(x)

for y in y_temp_test:
    print(y)

7
cinta
sedih
marah
takut
sedih
gembira
sedih


#### Text Preprocessing
---

In [50]:
X_temp_train_docs = clf.text_preprocessing_pipeline.transform(X_temp_train)
X_temp_validation_docs = clf.text_preprocessing_pipeline.transform(X_temp_validation)
X_temp_test_docs = clf.text_preprocessing_pipeline.transform(X_temp_test)

2023-06-25 09:25:26 INFO: TEXT CLEANING
2023-06-25 09:25:26 INFO: TOKENIZE, MWT, POS, LEMMA
2023-06-25 09:25:26 INFO: TEXT CLEANING
2023-06-25 09:25:26 INFO: TOKENIZE, MWT, POS, LEMMA
2023-06-25 09:25:26 INFO: TEXT CLEANING
2023-06-25 09:25:26 INFO: TOKENIZE, MWT, POS, LEMMA


#### Feature Selection
---

In [14]:
clf.feature_selection_pipeline.named_steps["pos_filter"].set_params(**{"pos": set(["ADJ","ADV","NOUN","PART","VERB"])})
clf.feature_selection_pipeline.named_steps["document_transformer"].set_params(**{"feat_attrs": ["lemma","upos"]})
X_temp_train_selected = clf.feature_selection_pipeline.transform(X_temp_train_docs)
X_temp_validation_selected = clf.feature_selection_pipeline.transform(X_temp_validation_docs)
X_temp_test_selected = clf.feature_selection_pipeline.transform(X_temp_test_docs)

2023-06-24 14:35:08 INFO: POS REMOVAL
2023-06-24 14:35:08 INFO: DOCUMENT TRANSFORMER
2023-06-24 14:35:08 INFO: POS REMOVAL
2023-06-24 14:35:08 INFO: DOCUMENT TRANSFORMER
2023-06-24 14:35:08 INFO: POS REMOVAL
2023-06-24 14:35:08 INFO: DOCUMENT TRANSFORMER


In [15]:
for i, doc in enumerate(X_temp_train_selected):
    print(", ".join(doc))

ketakutan.ADJ, gugup.ADJ
kesepian.NOUN, terisolasi.VERB
bangun.VERB, kesal.ADJ
sedih.ADJ
sedih.ADJ, harap.VERB, mati.ADJ
teriak.VERB, marah.ADJ
marah.VERB
senang.VERB
senang.ADJ
takut.ADJ, bodoh.ADJ
seram.VERB, lihat.VERB
bodoh.ADJ, malu.ADJ
takut.ADJ
bodoh.ADJ, gugup.ADJ
rugi.VERB
orang.NOUN, bodoh.ADJ
bodoh.ADJ
sambut.VERB, cinta.VERB
bodoh.NOUN, senang.ADJ


In [16]:
for i, doc in enumerate(X_temp_validation_selected):
    print(", ".join(doc))

suka.VERB, takut.ADJ
gemetar.ADJ, sedih.ADJ
senang.ADJ, lelah.ADJ
kesal.ADJ
cinta.VERB
sedih.ADJ, pikir.VERB


In [17]:
for i, doc in enumerate(X_temp_test_selected):
    print(", ".join(doc))

cinta.NOUN, hati.NOUN
bodoh.ADJ, jujur.ADJ
kesal.ADJ, marah.VERB
takut.ADJ
patah.ADJ, hati.NOUN, sedih.ADJ
senang.ADJ, minggu.NOUN
putus.ADJ, asa.ADJ, sedih.ADJ


#### Feature Extraction
---

In [18]:
tfidfvectorizer_hyperparameters = {
    "ngram_range": (1, 1),
    "max_df": (1.0),
    "min_df": (1),
    "norm": None,
    "sublinear_tf": False
}
tfidfvectorizer = clf.classification_pipeline.named_steps["tfidfvectorizer"]
tfidfvectorizer.set_params(**tfidfvectorizer_hyperparameters)
tfidfvectorizer.fit(X_temp_train_selected)

TfidfVectorizer(decode_error='ignore', encoding='ascii', norm=None,
                preprocessor=<function fun at 0x000002A3064CCE50>,
                strip_accents='ascii', token_pattern=None,
                tokenizer=<function fun at 0x000002A3064CCE50>)

In [19]:
for i, zip_ in enumerate(
    zip(
        dict(
            sorted(
                tfidfvectorizer.vocabulary_.items(),
                key=lambda x: x[1]
            )
        ).items(),
        tfidfvectorizer.idf_
    )
):
    item, idf = zip_
    k, v = item
    df = 0

    for doc in X_temp_train_selected:
        if k in doc:
            df+=1

    print(i+1, k, df, round(idf, 5), sep="\t")
    # print(i+1, k, df, sep="\t")

1	bangun.VERB	1	3.30259
2	bodoh.ADJ	5	2.20397
3	bodoh.NOUN	1	3.30259
4	cinta.VERB	1	3.30259
5	gugup.ADJ	2	2.89712
6	harap.VERB	1	3.30259
7	kesal.ADJ	1	3.30259
8	kesepian.NOUN	1	3.30259
9	ketakutan.ADJ	1	3.30259
10	lihat.VERB	1	3.30259
11	malu.ADJ	1	3.30259
12	marah.ADJ	1	3.30259
13	marah.VERB	1	3.30259
14	mati.ADJ	1	3.30259
15	orang.NOUN	1	3.30259
16	rugi.VERB	1	3.30259
17	sambut.VERB	1	3.30259
18	sedih.ADJ	2	2.89712
19	senang.ADJ	2	2.89712
20	senang.VERB	1	3.30259
21	seram.VERB	1	3.30259
22	takut.ADJ	2	2.89712
23	teriak.VERB	1	3.30259
24	terisolasi.VERB	1	3.30259


In [20]:
X_temp_train_features = tfidfvectorizer.transform(X_temp_train_selected)
X_temp_validation_features = tfidfvectorizer.transform(X_temp_validation_selected)
X_temp_test_features = tfidfvectorizer.transform(X_temp_test_selected)

#### Multi classification
---

In [21]:
linearsvc_hyperparameters = {
    "penalty": "l2",
    "loss": "squared_hinge",
    "dual": False,
    "tol": 0.0001,
    "C": 0.01,
    "multi_class": "ovr",
    "fit_intercept": True,
    "intercept_scaling": 1.0,
    "class_weight": "balanced",
    "max_iter": 1000
}
linearsvc = clf.classification_pipeline.named_steps["linearsvc"]
linearsvc.set_params(**linearsvc_hyperparameters)
linearsvc.fit(X_temp_train_features, y_temp_train)

LinearSVC(C=0.01, class_weight='balanced', dual=False, intercept_scaling=1.0,
          random_state=42)

In [22]:
y_temp_validation_pred = linearsvc.predict(X_temp_validation_features)
y_temp_test_pred = linearsvc.predict(X_temp_test_features)

#### Evaluation
---

In [23]:
from sklearn.metrics import accuracy_score, matthews_corrcoef

In [24]:
# test
print(accuracy_score(y_temp_validation, y_temp_validation_pred))
print(matthews_corrcoef(y_temp_validation, y_temp_validation_pred))

1.0
1.0


In [25]:
# test
print(accuracy_score(y_temp_test, y_temp_test_pred))
print(matthews_corrcoef(y_temp_test, y_temp_test_pred))

0.8571428571428571
0.8215838362577492


In [26]:
y_temp_test_pred

array(['sedih', 'sedih', 'marah', 'takut', 'sedih', 'gembira', 'sedih'],
      dtype='<U7')

In [27]:
clf.classification_pipeline.named_steps['linearsvc'].classes_

array(['cinta', 'gembira', 'marah', 'sedih', 'takut'], dtype='<U7')

In [96]:
coef=clf.classification_pipeline.named_steps['linearsvc'].coef_
coef

array([[-0.03813218, -0.10651256, -0.0344351 ,  0.11056692, -0.05658632,
        -0.02968064, -0.03813218, -0.03813218, -0.03607145, -0.03813218,
        -0.03223173, -0.03813218, -0.04496098, -0.02968064, -0.03223173,
        -0.04496098,  0.11056692, -0.06343311, -0.06700416, -0.04496098,
        -0.03813218, -0.06175401, -0.03813218, -0.03813218],
       [-0.04006461, -0.11191073,  0.05365017, -0.04006461, -0.05945411,
        -0.03118495, -0.04006461, -0.04006461, -0.03789952, -0.04006461,
        -0.03386518, -0.04006461, -0.0472393 , -0.03118495, -0.03386518,
        -0.0472393 , -0.04006461, -0.06664773,  0.10713096,  0.07399581,
        -0.04006461, -0.06488369, -0.04006461, -0.04006461],
       [ 0.04934563, -0.11402887, -0.03686546, -0.04082317, -0.06057963,
        -0.03177494,  0.04934563, -0.04082317, -0.03861675, -0.04082317,
        -0.0345063 ,  0.04934563,  0.05781501, -0.03177494, -0.0345063 ,
         0.05781501, -0.04082317, -0.06790886, -0.07173221, -0.0481335 ,
  

In [97]:
intercept=clf.classification_pipeline.named_steps['linearsvc'].intercept_
intercept

array([-0.17082486, -0.12880167, -0.11231436, -0.09502383, -0.12458426])

In [30]:
import numpy as np

In [98]:
i=18
np.dot(X_temp_train_features[i].toarray(), coef.T) + intercept.T

array([[-0.47866877,  0.35875383, -0.4418825 , -0.43100894, -0.44960332]])

In [99]:
np.dot(X_temp_train_features.toarray(), coef[1])

array([-0.29741209, -0.26463357, -0.26463357, -0.19308646, -0.39906837,
       -0.26463357, -0.1560118 ,  0.24437748,  0.31037124, -0.43462405,
       -0.26463357, -0.35849084, -0.18797583, -0.41889392, -0.1560118 ,
       -0.35849084, -0.24664822, -0.26463357,  0.48755549])

In [101]:
coef[1].T.shape

(24,)

In [71]:
X_temp_train_features.toarray().shape

(19, 24)

In [102]:
intercept[1]

-0.12880166530722365

In [149]:
coef[1]

array([-0.04006461, -0.11191073,  0.05365017, -0.04006461, -0.05945411,
       -0.03118495, -0.04006461, -0.04006461, -0.03789952, -0.04006461,
       -0.03386518, -0.04006461, -0.0472393 , -0.03118495, -0.03386518,
       -0.0472393 , -0.04006461, -0.06664773,  0.10713096,  0.07399581,
       -0.04006461, -0.06488369, -0.04006461, -0.04006461])

In [138]:
(np.dot(coef[1][1:], X_temp_train_features[-1].toarray()[0][1:]) - intercept[1]) / coef[1][0]

-15.384079449819701

In [146]:
(np.dot([v for i, v in enumerate(coef[1]) if i != 1], [v for i, v in enumerate(X_temp_train_features[-1].toarray()[0]) if i != 1]) - intercept[1]) / coef[1][1]

-5.507578517676394

In [137]:
(np.dot(coef[1][:-1], X_temp_train_features[-1].toarray()[0][:-1]) - intercept[1]) / coef[1][-1]

-15.384079449819701

In [163]:
2 / np.dot(coef[1].T, coef[1])

28.276029084166513